import 'package:flutter/material.dart';

final List<Map<String, dynamic>> colorList = [
  {'color': Colors.red},
  {'color': Colors.green},
  {'color': Colors.blue},
  {'color': Colors.yellow},
  {'color': Colors.purple},
  {'color': Colors.pink},
  {'color': Colors.orange},
  {'color': Colors.cyan},
  {'color': Colors.teal},
  {'color': Colors.brown},
  {'color': Colors.grey},
  {'color': Colors.indigo},
  {'color': Colors.lime},
  {'color': Colors.amber},
  {'color': Colors.deepOrange},
  {'color': Colors.deepPurple},
  {'color': Colors.lightBlue},
  {'color': Colors.lightGreen},
  {'color': Colors.orange},
  {'color': Colors.blueGrey},
  {'color': Colors.black},
  {'color': Colors.white},
  {'color': Colors.transparent},
];
